create table authorities
(
    id         int8 generated by default as identity,
    authority  varchar(20) not null ,
    customer_id int8 not null ,
    primary key (id)
);
create table customers
(
    id              int8 generated by default as identity,
    activation_code varchar(100),
    active          boolean,
    email           varchar(255),
    firstname       varchar(70),
    lastname        varchar(70),
    login           varchar(100) not null ,
    password        varchar(250) not null ,
    primary key (id)
);
create table messages
(
    id         int8 generated by default as identity,
    filename   varchar(255),
    tag        varchar(50),
    text       varchar(2048) not null ,
    customer_id int8,
    primary key (id)
);
alter table if exists authorities add constraint authority_customer_fk foreign key (customer_id) references customers;
alter table if exists messages add constraint message_customer_fk foreign key (customer_id) references customers;